### PR TITLE
Add lecture particle emission + new paper + typo

### PR DESCRIPTION
**Pull request by kafischer**
Removed duplicate entry for Hanschke et al., "Quantum dot single photon sources with ultra-low multi-photon probability".

Added new paper Fischer et al., "Particle emission from open-quantum systems"

Added link to new notebook from PR#54 in qutip-notebooks

### CODE REVIEW

**Comment by ajgpitch** [comment]
Thanks for making the link.
And spotting and fixing the typo.

**Comment by ajgpitch** [comment]
@kafischer actually there is something a little wrong with this.
The link text for your recent paper reads `arXiv:1801.10383` which is incorrect. However, it links to the correct arXiv entry.
Could you look at this please.

**Comment by kafischer** [comment]
Thanks for catching this! The correct identifier is arXiv:1803.04648.

**Comment by ajgpitch** [comment]
A new PR would be the correct method. However, I just edited the master and all is fine.

It's good practice actually to delete the branch after it has been merged, as it is effectively dead wood.

**Comment by kafischer** [comment]
Thanks!

**Pull request merged**
