### PR TITLE
Update Google Anaytics to use new QuTiP analyics tag

### PR DESCRIPTION
**Pull request by hodgestar**
* Removes the old Google Analytics tag.
* Adds the new Google Analytics tag.

### CODE REVIEW

**Comment by hodgestar** [comment]
If any QuTiP Admins would like to be added to the people who have access to the new Google Analytics account, please let me know.

**Comment by ajgpitch** [comment]
Looks fine to me. 
I am assuming that putting the tag in the header rather than footer is the recommended way to do it.
I am also assuming that there can be only one GA account assigned. Just a tiny bit concerned that the stats will be split across two accounts next year.

**Comment by hodgestar** [comment]
@ajgpitch Thanks for taking a look.

Re header: The header is the way Google recommended now. I think the footer is a legacy hangover from the days when browser Javascript engines were slower (so that delaying Javascript processing to later in the page loading process was a thing people did.

Re multiple GA tags: Good idea. If we can get the Google Analytics measurement property ID from Robert, I can just add another `gtag('config', 'GA_MEASUREMENT_ID_2');` line and that will report to both.

**Comment by hodgestar** [comment]
Merging after chatting to @ajgpitch via email. We'll combine results from the two GA accounts just this once (i.e. for 2022).

**Pull request merged**
